# Generated by Django 4.2.6 on 2023-10-30 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance', '0001_initial'),
        ('core', '0001_initial'),
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plancodification',
            name='codification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='medical.codification'),
        ),
        migrations.AddField(
            model_name='plancodification',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='insurance.membership'),
        ),
        migrations.AddField(
            model_name='plancategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='medical.category'),
        ),
        migrations.AddField(
            model_name='plancategory',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='insurance.membership'),
        ),
        migrations.AddField(
            model_name='patient',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.locality'),
        ),
        migrations.AddField(
            model_name='membership',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='policies', to='core.company'),
        ),
        migrations.AddField(
            model_name='decease',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='insurance.patient'),
        ),
        migrations.AddField(
            model_name='clainitem',
            name='care_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='medical.nomenclature'),
        ),
        migrations.AddField(
            model_name='clainitem',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='insurance.claim'),
        ),
        migrations.AddField(
            model_name='clainitem',
            name='pathology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='medical.pathology'),
        ),
        migrations.AddField(
            model_name='clainitem',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='insurance.patient'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='insurance.subscriber'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='grouping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.grouping'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='assign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='insurance.assign'),
        ),
        migrations.AlterUniqueTogether(
            name='plancodification',
            unique_together={('codification', 'membership')},
        ),
        migrations.AlterUniqueTogether(
            name='plancategory',
            unique_together={('category', 'membership')},
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('company', 'label')},
        ),
        migrations.AddField(
            model_name='claim',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='insurance.subscriber'),
        ),
        migrations.AddField(
            model_name='assign',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='assigns', to='insurance.subscription'),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('subscriber', 'membership')},
        ),
    ]
