# Generated by Django 4.2.4 on 2023-08-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_standing_practionner_isactive_practionner_speciality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practionner',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='degree',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standing',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
