# Generated by Django 4.2.4 on 2023-08-25 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_remove_subscriptionplan_delayamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plancategory',
            name='ageLimit',
            field=models.PositiveSmallIntegerField(default=0, help_text='Age limitation for allowing the service', verbose_name='Age limit'),
        ),
        migrations.AlterField(
            model_name='plancategory',
            name='familyMaxiService',
            field=models.PositiveSmallIntegerField(help_text='Maximum nummber services per family', verbose_name='Maxi Svce/Family'),
        ),
        migrations.AlterField(
            model_name='plancategory',
            name='individualMaxiService',
            field=models.PositiveSmallIntegerField(help_text='Maximum number services per Person', verbose_name='Maxi Svce/Person'),
        ),
        migrations.AlterField(
            model_name='plancategory',
            name='serviceTimeOut',
            field=models.PositiveSmallIntegerField(help_text='Waiting delay after registering in days!', verbose_name='Timeout'),
        ),
        migrations.AlterField(
            model_name='plancategory',
            name='waitingDelay',
            field=models.PositiveSmallIntegerField(help_text='Delay between two (2) services in days!', verbose_name='Waiting delay'),
        ),
        migrations.AlterField(
            model_name='plancodification',
            name='claimRate',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Claim Rate'),
        ),
        migrations.AlterField(
            model_name='plancodification',
            name='privateRate',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Private Rate'),
        ),
        migrations.AlterField(
            model_name='plancodification',
            name='publicRate',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Public Rate'),
        ),
        migrations.AlterField(
            model_name='plancodification',
            name='waitingDelay',
            field=models.PositiveSmallIntegerField(help_text='Waiting delay in days.', verbose_name='Waiting Delay'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='additionalChild',
            field=models.PositiveSmallIntegerField(help_text='Allowed Child Limited Number allowed!', verbose_name='Additional Child'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='additionalSpouse',
            field=models.PositiveSmallIntegerField(help_text='Allowed Spouse Limited Number allowed!', verbose_name='Additional Spouse'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='childAgeLimit',
            field=models.PositiveSmallIntegerField(help_text='Child Age Limit allowance', verbose_name='Child Age Limit'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='childMajority',
            field=models.PositiveSmallIntegerField(help_text='Majority Age of child', verbose_name='Child Majority Age'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='childMaxi',
            field=models.PositiveSmallIntegerField(help_text='Allowed Child Limited Number allowed!', verbose_name='Maximum Child'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='claimDelay',
            field=models.PositiveSmallIntegerField(help_text='Delay in days', verbose_name='Claim Delay'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='maxClaim',
            field=models.PositiveSmallIntegerField(help_text='Maximum number of claims allowed', verbose_name='Max Claim'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='memberAgeLimit',
            field=models.PositiveSmallIntegerField(help_text='Member Age Limit allowance', verbose_name='Member Age Limit'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='privateClaim',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Private Claim'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='privateCoverage',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Private Coverage'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='publicClaim',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Public Claim'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='publicCoverage',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Public Coverage'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='spouseAgeLimit',
            field=models.PositiveSmallIntegerField(help_text='Spouse Age Limit allowance', verbose_name='Spouse Age Limit'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='spouseMaxi',
            field=models.PositiveSmallIntegerField(help_text='Allowed Spouse Limited Number allowed!', verbose_name='Maximum Spouse'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='validityDelay',
            field=models.PositiveSmallIntegerField(help_text='Medical Care Validity Delay!', verbose_name='Validity'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='waitingDelay',
            field=models.PositiveSmallIntegerField(default=0, help_text='Waiting delay in days.', verbose_name='Waiting Delay'),
        ),
    ]
