# Generated by Django 4.2.4 on 2023-08-26 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
        ('insurance', '0002_plancategory_category_plancodification_codification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plancategory',
            options={'verbose_name_plural': 'Plan Categories'},
        ),
        migrations.RenameField(
            model_name='scholarship',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='scholarship',
            old_name='beginDate',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='suspension',
            old_name='begin_date',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='assign',
            name='deceased_at',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='deceased_at',
        ),
        migrations.AlterUniqueTogether(
            name='plancategory',
            unique_together={('category', 'subscription_plan')},
        ),
        migrations.AlterUniqueTogether(
            name='plancodification',
            unique_together={('codification', 'subscription_plan')},
        ),
        migrations.CreateModel(
            name='Decease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deceased_at', models.DateField(verbose_name='Deceased at')),
                ('note', models.TextField(blank=True, null=True)),
                ('assisgn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='insurance.assign')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='insurance.subscriber')),
            ],
        ),
    ]
