# Generated by Django 4.2.4 on 2023-08-22 20:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_degree_standing_and_more'),
        ('core', '0002_alter_locality_options_and_more'),
        ('insurance', '0003_practionner_note_alter_degree_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('validityDelay', models.PositiveIntegerField(help_text='Medical Care Validity Delay!', verbose_name='Validity')),
                ('delayAmount', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Delay Amount')),
                ('isGenderControl', models.BooleanField(default=True, verbose_name='Is Gender Control')),
                ('waitingPeriod', models.PositiveIntegerField(verbose_name='Waiting Period')),
                ('individualCeiling', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Individual Ceiling')),
                ('familyCeiling', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Family Ceiling')),
                ('privateCoverage', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Private Coverage')),
                ('publicCoverage', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Public Coverage')),
                ('publicClaim', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Public Claim')),
                ('privateClaim', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Private Claim')),
                ('claimDelay', models.PositiveIntegerField(help_text='Delay in days', verbose_name='Claim Delay')),
                ('maxClaim', models.PositiveIntegerField(help_text='Maximum number of claims allowed', verbose_name='Max Claim')),
                ('claimCeilling', models.DecimalField(decimal_places=0, help_text='Claim Ceilling Amount', max_digits=9, verbose_name='Claim Ceilling')),
                ('individualClaimCeiling', models.DecimalField(decimal_places=0, help_text='Individual Claim Ceiling Amount', max_digits=9, verbose_name='Individual Claim Ceiling')),
                ('familyClaimCeiling', models.DecimalField(decimal_places=0, help_text='Family Claim Ceiling Amount', max_digits=9, verbose_name='Family Claim Ceiling')),
                ('memberAgeLimit', models.PositiveIntegerField(help_text='Member Age Limit allowance', verbose_name='Member Age Limit')),
                ('childAgeLimit', models.PositiveIntegerField(help_text='Child Age Limit allowance', verbose_name='Child Age Limit')),
                ('additionalChild', models.PositiveIntegerField(help_text='Allowed Child Limited Number allowed!', verbose_name='Additional Child')),
                ('childMaxi', models.PositiveIntegerField(help_text='Allowed Child Limited Number allowed!', verbose_name='Maximum Child')),
                ('childMajority', models.PositiveIntegerField(help_text='Majority Age of child', verbose_name='Child Majority Age')),
                ('spouseAgeLimit', models.PositiveIntegerField(help_text='Spouse Age Limit allowance', verbose_name='Spouse Age Limit')),
                ('additionalSpouse', models.PositiveIntegerField(help_text='Allowed Spouse Limited Number allowed!', verbose_name='Additional Spouse')),
                ('spouseMaxi', models.PositiveIntegerField(help_text='Allowed Spouse Limited Number allowed!', verbose_name='Maximum Spouse')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='policies', to='core.company')),
                ('standing', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='medical.standing')),
            ],
            options={
                'unique_together': {('company', 'label')},
            },
        ),
        migrations.CreateModel(
            name='ProductCodificationConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicRate', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Public Rate')),
                ('privateRate', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Private Rate')),
                ('claimRate', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Claim Rate')),
                ('individualCeiling', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Indidual Ceiling')),
                ('familyCeiling', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Family Ceiling')),
                ('ceilingAmount', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Ceiling Amount')),
                ('waitingDelay', models.PositiveIntegerField(help_text='Waiting delay in days.', verbose_name='Waiting Delay')),
                ('isStrict', models.BooleanField(default=False, verbose_name='Is strict')),
                ('codification', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='medical.codification')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='insurance.product')),
            ],
            options={
                'unique_together': {('codification', 'product')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='practionner',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='practionner',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='practionner',
            name='speciality',
        ),
        migrations.DeleteModel(
            name='Standing',
        ),
        migrations.DeleteModel(
            name='Degree',
        ),
        migrations.DeleteModel(
            name='Practionner',
        ),
    ]
