# Generated by Django 4.2.6 on 2023-10-23 18:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical', '0001_initial'),
        ('insurance', '0003_membership_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='plancategory',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='plancodification',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='assign',
            name='police',
        ),
        migrations.AddField(
            model_name='membership',
            name='additional_child',
            field=models.PositiveSmallIntegerField(default=0, help_text='Allowed Child Limited Number allowed!', verbose_name='Additional Child'),
        ),
        migrations.AddField(
            model_name='membership',
            name='additional_spouse',
            field=models.PositiveSmallIntegerField(default=0, help_text='Allowed Spouse Limited Number allowed!', verbose_name='Additional Spouse'),
        ),
        migrations.AddField(
            model_name='membership',
            name='child_age_limit',
            field=models.PositiveSmallIntegerField(default=0, help_text='Child Age Limit allowance', verbose_name='Child Age Limit'),
        ),
        migrations.AddField(
            model_name='membership',
            name='child_majority',
            field=models.PositiveSmallIntegerField(default=0, help_text='Majority Age of child', verbose_name='Child Majority Age'),
        ),
        migrations.AddField(
            model_name='membership',
            name='child_maxi',
            field=models.PositiveSmallIntegerField(default=0, help_text='Allowed Child Limited Number allowed!', verbose_name='Maximum Child'),
        ),
        migrations.AddField(
            model_name='membership',
            name='claim_ceilling',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Claim Ceilling Amount', max_digits=9, verbose_name='Claim Ceilling'),
        ),
        migrations.AddField(
            model_name='membership',
            name='claim_delay',
            field=models.PositiveSmallIntegerField(default=0, help_text='Delay in days', verbose_name='Claim Delay'),
        ),
        migrations.AddField(
            model_name='membership',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, related_name='policies', to='core.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membership',
            name='family_ceiling',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9, verbose_name='Family Ceiling'),
        ),
        migrations.AddField(
            model_name='membership',
            name='family_claim_ceiling',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Family Claim Ceiling Amount', max_digits=9, verbose_name='Family Claim Ceiling'),
        ),
        migrations.AddField(
            model_name='membership',
            name='individual_ceiling',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9, verbose_name='Individual Ceiling'),
        ),
        migrations.AddField(
            model_name='membership',
            name='individual_claim_ceiling',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Individual Claim Ceiling Amount', max_digits=9, verbose_name='Individual Claim Ceiling'),
        ),
        migrations.AddField(
            model_name='membership',
            name='insurance_premium',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9, verbose_name='Insurance Premium'),
        ),
        migrations.AddField(
            model_name='membership',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='is_gender_gontrol',
            field=models.BooleanField(default=True, verbose_name='Is Gender Control'),
        ),
        migrations.AddField(
            model_name='membership',
            name='label',
            field=models.CharField(default='', max_length=255, verbose_name='Label'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membership',
            name='max_claim',
            field=models.PositiveSmallIntegerField(default=0, help_text='Maximum number of claims allowed', verbose_name='Max Claim'),
        ),
        migrations.AddField(
            model_name='membership',
            name='member_age_limit',
            field=models.PositiveSmallIntegerField(default=0, help_text='Member Age Limit allowance', verbose_name='Member Age Limit'),
        ),
        migrations.AddField(
            model_name='membership',
            name='min_tolerated_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6, verbose_name='Min. Tolerated Amount'),
        ),
        migrations.AddField(
            model_name='membership',
            name='name',
            field=models.CharField(default='', max_length=64, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membership',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='premium_cycle',
            field=models.IntegerField(choices=[(0, 'Daily'), (1, 'Weekly'), (2, 'Fortnight'), (3, 'Monthly'), (4, 'Quaterly'), (5, 'Half-yearly'), (6, 'Yearly')], default=None, verbose_name='Premium Cycle'),
        ),
        migrations.AddField(
            model_name='membership',
            name='private_claim',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Private Claim'),
        ),
        migrations.AddField(
            model_name='membership',
            name='private_coverage',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Private Coverage'),
        ),
        migrations.AddField(
            model_name='membership',
            name='public_claim',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Public Claim'),
        ),
        migrations.AddField(
            model_name='membership',
            name='public_coverage',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Public Coverage'),
        ),
        migrations.AddField(
            model_name='membership',
            name='spouse_age_limit',
            field=models.PositiveSmallIntegerField(default=0, help_text='Spouse Age Limit allowance', verbose_name='Spouse Age Limit'),
        ),
        migrations.AddField(
            model_name='membership',
            name='spouse_maxi',
            field=models.PositiveSmallIntegerField(default=0, help_text='Allowed Spouse Limited Number allowed!', verbose_name='Maximum Spouse'),
        ),
        migrations.AddField(
            model_name='membership',
            name='standing',
            field=models.IntegerField(choices=[(0, '★'), (1, '★★'), (2, '★★★'), (3, '★★★★'), (4, '★★★★★')], default=None, verbose_name='Standing'),
        ),
        migrations.AddField(
            model_name='membership',
            name='validity_delay',
            field=models.PositiveSmallIntegerField(default=0, help_text='Medical Care Validity Delay!', verbose_name='Validity'),
        ),
        migrations.AddField(
            model_name='membership',
            name='waiting_delay',
            field=models.PositiveSmallIntegerField(default=0, help_text='Waiting delay in days.', verbose_name='Waiting Delay'),
        ),
        migrations.AddField(
            model_name='plancategory',
            name='membership',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='insurance.membership'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plancodification',
            name='membership',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='insurance.membership'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('company', 'label')},
        ),
        migrations.AlterUniqueTogether(
            name='plancategory',
            unique_together={('category', 'membership')},
        ),
        migrations.AlterUniqueTogether(
            name='plancodification',
            unique_together={('codification', 'membership')},
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Police ID.')),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='insurance.membership')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='insurance.subscriber')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('subscriber', 'membership')},
            },
        ),
        migrations.RemoveField(
            model_name='membership',
            name='begin_date',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='police',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='subscriber',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='subscription_plan',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='plancategory',
            name='subscription_plan',
        ),
        migrations.RemoveField(
            model_name='plancodification',
            name='subscription_plan',
        ),
        migrations.AddField(
            model_name='assign',
            name='subscription',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, related_name='assigns', to='insurance.subscription'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
