# Generated by Django 4.2.4 on 2023-08-29 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_practitioner_photo'),
        ('insurance', '0004_assign_photo_decease_document_scholarship_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_reference', models.CharField(blank=True, max_length=24, null=True, verbose_name='Doc. Reference')),
                ('requested_at', models.DateField(verbose_name='Requested Date')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Creation Date')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified Date')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='insurance.subscriber')),
            ],
        ),
        migrations.AddField(
            model_name='suspension',
            name='subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='insurance.subscriber'),
        ),
        migrations.AlterField(
            model_name='decease',
            name='subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='insurance.subscriber'),
        ),
        migrations.AlterField(
            model_name='suspension',
            name='assign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='insurance.assign'),
        ),
        migrations.CreateModel(
            name='ClainItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_center', models.CharField(max_length=255)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Creation Date')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified Date')),
                ('note', models.TextField(blank=True, null=True)),
                ('assign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='insurance.assign')),
                ('care_service', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='medical.nomenclature')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='insurance.claim')),
                ('pathology', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='medical.pathology')),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='insurance.subscriber')),
            ],
        ),
    ]
