# Generated by Django 4.2.4 on 2023-08-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_degree_standing_and_more'),
        ('insurance', '0005_plancategory_plancodification_subscriptionplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plancategory',
            name='familyMaxiService',
            field=models.PositiveIntegerField(help_text='Maximum nummber services per family', verbose_name='Maxi Svce/Family'),
        ),
        migrations.AlterField(
            model_name='plancategory',
            name='individualMaxiService',
            field=models.PositiveIntegerField(help_text='Maximum number services per Person', verbose_name='Maxi Svce/Person'),
        ),
        migrations.AlterField(
            model_name='plancategory',
            name='serviceTimeOut',
            field=models.PositiveIntegerField(help_text='Waiting delay after registering in days!', verbose_name='Timeout'),
        ),
        migrations.AlterField(
            model_name='plancategory',
            name='waitingDelay',
            field=models.PositiveIntegerField(help_text='Delay between two (2) services in days!', verbose_name='Waiting delay'),
        ),
        migrations.AlterUniqueTogether(
            name='plancategory',
            unique_together={('category', 'subscriptionPlan')},
        ),
    ]
