# Generated by Django 4.2.4 on 2023-08-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_alter_plancategory_familymaxiservice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plancategory',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'All')], default=None, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='plancategory',
            name='relationship',
            field=models.IntegerField(choices=[(0, 'Member'), (1, 'Spouse'), (2, 'Child'), (3, 'Member + Spouse'), (4, 'Member + Child'), (5, 'Spouse + Child'), (6, 'All')], default=None, verbose_name='Relationship'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='feesCycle',
            field=models.IntegerField(choices=[(0, 'Daily'), (1, 'Weekly'), (2, 'Fortnight'), (3, 'Monthly'), (4, 'Quaterly'), (5, 'Half-yearly'), (6, 'Yearly')], default=None),
        ),
    ]
