# Generated by Django 4.2.4 on 2023-08-25 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0007_alter_plancategory_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='feesCycle',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='subscriptionFees',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='insurancePremium',
            field=models.DecimalField(decimal_places=0, default=datetime.date.today, max_digits=9, verbose_name='Insurance Premium'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='premiumCycle',
            field=models.IntegerField(choices=[(0, 'Daily'), (1, 'Weekly'), (2, 'Fortnight'), (3, 'Monthly'), (4, 'Quaterly'), (5, 'Half-yearly'), (6, 'Yearly')], default=None, verbose_name='Premium Cycle'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='standing',
            field=models.IntegerField(choices=[(0, '*'), (1, '**'), (2, '***'), (3, '****'), (4, '*****')], default=None, verbose_name='Standing'),
        ),
    ]
