# Generated by Django 4.2.6 on 2023-10-30 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='health_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='medical.healthcenter'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('name', 'district')},
        ),
        migrations.AlterUniqueTogether(
            name='locality',
            unique_together={('name', 'region')},
        ),
        migrations.AlterUniqueTogether(
            name='grouping',
            unique_together={('name', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='exercice',
            unique_together={('title', 'company')},
        ),
    ]
