# Generated by Django 4.2.4 on 2023-08-24 10:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='create_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriber',
            name='idCode',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True, verbose_name='ID. Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriber',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='modified_at',
            field=models.DateField(auto_now=True, verbose_name='Modified Date'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='bloodGrp',
            field=models.IntegerField(blank=True, choices=[(0, 'A+'), (1, 'A-'), (2, 'B+'), (3, 'B-'), (4, 'AB+'), (5, 'AB-'), (6, 'O+'), (7, 'O-')], default=None, null=True),
        ),
    ]
