# Generated by Django 4.2.4 on 2023-08-24 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0007_alter_plancategory_gender_and_more'),
        ('membership', '0002_subscriber_create_at_subscriber_idcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Police',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_at', models.DateField(auto_now_add=True)),
                ('end_at', models.DateField(blank=True, null=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='membership.subscriber')),
                ('subscriptionPlan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='insurance.subscriptionplan')),
            ],
            options={
                'unique_together': {('subscriber', 'subscriptionPlan')},
            },
        ),
    ]
