# Generated by Django 4.2.4 on 2023-08-24 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_alter_assign_idcode_alter_subscriber_idcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='police',
            old_name='end_at',
            new_name='endDate',
        ),
        migrations.RemoveField(
            model_name='police',
            name='begin_at',
        ),
        migrations.AddField(
            model_name='police',
            name='beginDate',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
    ]
