# Generated by Django 4.2.4 on 2023-08-26 19:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Codification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('label', models.CharField(max_length=64)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Degree name')),
                ('isA_ative', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_reference', models.CharField(blank=True, max_length=24, null=True, verbose_name='Doc. Reference')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Creation Date')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified Date')),
                ('note', models.TextField(blank=True, null=True)),
                ('assign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='insurance.assign')),
            ],
        ),
        migrations.CreateModel(
            name='HealthCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('acronym', models.CharField(max_length=32, unique=True)),
                ('standing', models.IntegerField(choices=[(0, '*'), (1, '**'), (2, '***'), (3, '****'), (4, '*****')], default=None, verbose_name='Standing')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('address', models.CharField(max_length=64, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Creation Date')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified Date')),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('center_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='medical.centertype')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='International NonProprietary Name', max_length=64, unique=True)),
                ('code', models.CharField(help_text='International NonProprietary Code', max_length=64)),
                ('dosage', models.CharField(help_text='Set the dosage of the pharmaceutical product', max_length=64)),
                ('indicative_price', models.DecimalField(decimal_places=0, default=0, max_digits=9)),
                ('price_margin', models.DecimalField(decimal_places=0, default=0, max_digits=9)),
                ('product_timout', models.PositiveSmallIntegerField()),
                ('minimum_age', models.PositiveSmallIntegerField()),
                ('maximum_age', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('coefficient', models.IntegerField(default=1)),
                ('service_timeout', models.IntegerField(help_text='Service waiting delay in days.', verbose_name='Service Timeout')),
                ('minimum_age', models.IntegerField(help_text='minimum age requirement allowed of this service', verbose_name='Minimum age')),
                ('maximum_age', models.IntegerField(help_text='maximum age requirement allowed of this service', verbose_name='Maximum age')),
                ('is_required_quantity', models.BooleanField(help_text='Is quantity required for this service?')),
                ('is_price_required', models.BooleanField(default=True, help_text='Price required for this service?', verbose_name='Price Required')),
                ('is_prior_agreement', models.BooleanField(help_text='Prior agreement is required for this service?', verbose_name='Prior agreement')),
                ('note', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('codification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medical.codification')),
            ],
            options={
                'unique_together': {('code', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Specialities',
            },
        ),
        migrations.CreateModel(
            name='TherapeuticRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('note', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('insurance_fixed_part', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('insured_fixed_part', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rebate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('coverage', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_not_check', models.BooleanField(default=False, help_text='This service medical code is not for check.')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Creation Date')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified Date')),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('healthcenter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='services', to='medical.healthcenter')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='medical.nomenclature')),
            ],
        ),
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CorpReference', models.CharField(max_length=32)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=128)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=None)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('degree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medical.degree')),
                ('speciality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medical.speciality')),
            ],
            options={
                'unique_together': {('first_name', 'last_name', 'date_of_birth')},
            },
        ),
        migrations.CreateModel(
            name='Pathology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('is_chronic', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medical.speciality')),
            ],
            options={
                'verbose_name_plural': 'Pathologies',
            },
        ),
        migrations.CreateModel(
            name='MedicationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplied_at', models.DateField(auto_now_add=True, verbose_name='Supply Date')),
                ('is_substitute', models.BooleanField(default=False)),
                ('prescribed', models.CharField(blank=True, max_length=128, null=True, verbose_name='prescribed medication')),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Creation Date')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified Date')),
                ('note', models.TextField(blank=True, null=True)),
                ('healthcare', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='medical.healthcare')),
                ('medication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='medical.medication')),
            ],
        ),
        migrations.AddField(
            model_name='medication',
            name='medication_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medical.medicationtype'),
        ),
        migrations.AddField(
            model_name='medication',
            name='molecule',
            field=models.ManyToManyField(to='medical.molecule'),
        ),
        migrations.AddField(
            model_name='medication',
            name='therapeutic_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medical.therapeuticroute'),
        ),
        migrations.AddField(
            model_name='healthcenter',
            name='staff',
            field=models.ManyToManyField(blank=True, to='medical.practitioner'),
        ),
        migrations.CreateModel(
            name='HealthCareItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplied_at', models.DateField(auto_now_add=True, verbose_name='Supply Date')),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Creation Date')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified Date')),
                ('note', models.TextField(blank=True, null=True)),
                ('healthcare', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='medical.healthcare')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='medical.service')),
            ],
        ),
        migrations.AddField(
            model_name='healthcare',
            name='mr_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='medical.healthcenter'),
        ),
        migrations.AddField(
            model_name='healthcare',
            name='subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='insurance.subscriber'),
        ),
        migrations.AddField(
            model_name='codification',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.medicinecategory'),
        ),
        migrations.AlterUniqueTogether(
            name='medication',
            unique_together={('name', 'medication_type', 'therapeutic_route')},
        ),
        migrations.AlterUniqueTogether(
            name='healthcenter',
            unique_together={('acronym', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='codification',
            unique_together={('code', 'category')},
        ),
    ]
