# Generated by Django 4.2.4 on 2023-08-16 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2, unique=True)),
                ('note', models.TextField()),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('note', models.TextField()),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Codification',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('label', models.CharField(max_length=64)),
                ('note', models.TextField()),
                ('isActive', models.BooleanField(default=True)),
                ('category', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='medical.category')),
            ],
            options={
                'unique_together': {('code', 'category')},
            },
        ),
        migrations.CreateModel(
            name='MedicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('note', models.TextField()),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('note', models.TextField()),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('note', models.TextField()),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TherapeuticRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('note', models.TextField()),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pathology',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('is_chronic', models.BooleanField(default=False)),
                ('note', models.TextField()),
                ('isActive', models.BooleanField(default=True)),
                ('speciality', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='medical.speciality')),
            ],
            options={
                'verbose_name_plural': 'Pathologies',
            },
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('coefficient', models.IntegerField(default=1)),
                ('waiting_period', models.IntegerField()),
                ('minimum_age', models.IntegerField()),
                ('maximum_age', models.IntegerField()),
                ('is_quantity_required', models.BooleanField(
                    help_text='Is quantity is required for this service?')),
                ('is_editable_price', models.BooleanField()),
                ('is_prior_agreement', models.BooleanField()),
                ('note', models.TextField()),
                ('isActive', models.BooleanField(default=True)),
                ('codification', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='medical.codification')),
            ],
            options={
                'unique_together': {('code', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(
                    help_text='International NonProprietary Name', max_length=64, unique=True)),
                ('code', models.CharField(
                    help_text='International NonProprietary Code', max_length=64)),
                ('dosage', models.CharField(
                    help_text='Set the dosage of the pharmaceutical product', max_length=64)),
                ('indicative_price', models.DecimalField(
                    decimal_places=0, max_digits=9)),
                ('price_margin', models.DecimalField(
                    decimal_places=0, max_digits=9)),
                ('waiting_period', models.IntegerField()),
                ('minimum_age', models.IntegerField()),
                ('maximum_age', models.IntegerField()),
                ('isActive', models.BooleanField(default=True)),
                ('note', models.TextField()),
                ('medication_type', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='medical.medicationtype')),
                ('molecule', models.ManyToManyField(
                    blank=True, null=True, to='medical.molecule')),
                ('therapeutic_route', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.PROTECT, to='medical.therapeuticroute')),
            ],
            options={
                'unique_together': {('name', 'medication_type', 'therapeutic_route')},
            },
        ),
    ]
