# Generated by Django 4.2.6 on 2023-10-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcenter',
            name='standing',
        ),
        migrations.AddField(
            model_name='agreement',
            name='standing',
            field=models.IntegerField(choices=[(0, '★'), (1, '★★'), (2, '★★★'), (3, '★★★★'), (4, '★★★★★')], default=None, verbose_name='Standing'),
        ),
    ]
