# Generated by Django 4.2.4 on 2023-08-28 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcenter',
            name='staff',
        ),
        migrations.AddField(
            model_name='healthcare',
            name='pathology',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='medical.pathology'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Creation Date')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified Date')),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('healthcenter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='medical.healthcenter')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='medical.practitioner')),
            ],
        ),
        migrations.AddField(
            model_name='healthcare',
            name='staff',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='medical.staff'),
            preserve_default=False,
        ),
    ]
