# Generated by Django 4.2.6 on 2023-11-26 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careitem',
            name='health_center',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, related_name='care_items', to='medical.healthcenter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='careondemand',
            name='health_center',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, related_name='on_demand_care_items', to='medical.healthcenter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicationitem',
            name='delivered_at',
            field=models.DateField(auto_now_add=True, default='', verbose_name='Delivered Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='careitem',
            name='service',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, related_name='care_items', to='medical.careservice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='careondemand',
            name='care_service',
            field=models.ForeignKey(limit_choices_to={'is_prior_agreement': True}, on_delete=django.db.models.deletion.RESTRICT, related_name='on_demand_care_items', to='medical.nomenclature'),
        ),
        migrations.AlterField(
            model_name='careondemand',
            name='health_care',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='on_demand_care_items', to='medical.healthcare'),
        ),
        migrations.AlterField(
            model_name='healthcare',
            name='status',
            field=models.PositiveBigIntegerField(choices=[(0, 'Consultation'), (1, 'Dispensation'), (2, 'Orientation'), (3, 'Expired'), (4, 'Completed')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='medicationitem',
            name='medication',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, related_name='medication_items', to='medical.medication'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicationitem',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='medication_items', to='medical.healthcenter'),
        ),
    ]
