# Generated by Django 4.2.4 on 2023-08-25 13:54

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('acronym', models.CharField(max_length=32, unique=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('address', models.CharField(max_length=64, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Creation Date')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified Date')),
                ('isActive', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('staff', models.ManyToManyField(blank=True, to='medical.practionner')),
            ],
            options={
                'unique_together': {('acronym', 'country')},
            },
        ),
        migrations.RemoveField(
            model_name='nomenclature',
            name='is_editable_price',
        ),
        migrations.RemoveField(
            model_name='nomenclature',
            name='is_prior_agreement',
        ),
        migrations.RemoveField(
            model_name='nomenclature',
            name='is_quantity_required',
        ),
        migrations.RemoveField(
            model_name='nomenclature',
            name='maximum_age',
        ),
        migrations.RemoveField(
            model_name='nomenclature',
            name='minimum_age',
        ),
        migrations.RemoveField(
            model_name='nomenclature',
            name='waiting_period',
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='isPriceRequired',
            field=models.BooleanField(default=True, help_text='Price required for this service?', verbose_name='Price Required'),
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='isPriorAgreement',
            field=models.BooleanField(default=True, help_text='Prior agreement is required for this service?', verbose_name='Prior agreement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='isRequiredQuantity',
            field=models.BooleanField(default=True, help_text='Is quantity required for this service?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='maximumAge',
            field=models.IntegerField(default=0, help_text='maximum age requirement allowed of this service', verbose_name='Maximum age'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='minimumAge',
            field=models.IntegerField(default=0, help_text='minimum age requirement allowed of this service', verbose_name='Minimum age'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='serviceTimeout',
            field=models.IntegerField(default=0, help_text='Service waiting delay in days.', verbose_name='Service Timeout'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medication',
            name='indicativePrice',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='medication',
            name='maximumAge',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='medication',
            name='minimumAge',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='medication',
            name='priceMargin',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='medication',
            name='waitingPeriod',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitPrice', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('insurancePart', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('insuredPart', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Creation Date')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified Date')),
                ('isActive', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('healthcenter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='services', to='medical.healthcenter')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='medical.nomenclature')),
            ],
        ),
    ]
