# Generated by Django 4.2.4 on 2023-08-28 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_remove_healthcenter_staff_healthcare_pathology_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='healthcenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='services', to='medical.healthcenter', verbose_name='Health Center'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='healthcenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='medical.healthcenter', verbose_name='Health Center'),
        ),
    ]
