# Generated by Django 4.2.6 on 2023-10-25 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_remove_healthcenter_standing_agreement_standing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcare',
            name='mrc_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT,
                                    related_name='mrc_center', to='medical.healthcenter'),
        ),
        migrations.AlterField(
            model_name='healthcare',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT,
                                    related_name='pharmacy', to='medical.healthcenter'),
        ),
        migrations.AlterField(
            model_name='healthcare',
            name='src_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT,
                                    related_name='src_center', to='medical.healthcenter'),
        ),
        migrations.AlterField(
            model_name='medicationitem',
            name='pharmacy',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to='medical.healthcenter'),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='is_prior_agreement',
            field=models.BooleanField(
                default=True, help_text='Prior agreement is required for this service?', verbose_name='Prior agreement'),
        ),
        migrations.CreateModel(
            name='CareOnDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('supplied_at', models.DateField(
                    auto_now_add=True, verbose_name='Supply Date')),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('unit_price', models.DecimalField(
                    decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateField(
                    auto_now_add=True, verbose_name='Creation Date')),
                ('modified_at', models.DateField(
                    auto_now=True, verbose_name='Modified Date')),
                ('note', models.TextField(blank=True, null=True)),
                ('care_service', models.ForeignKey(limit_choices_to={
                 'is_prior_agreement': True}, on_delete=django.db.models.deletion.RESTRICT, to='medical.nomenclature')),
                ('health_care', models.ForeignKey(
                    on_delete=django.db.models.deletion.RESTRICT, to='medical.healthcare')),
            ],
        ),
    ]
