# Generated by Django 4.2.4 on 2023-08-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_alter_speciality_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='molecule',
            field=models.ManyToManyField(to='medical.molecule'),
        ),
    ]
