# Generated by Django 4.2.6 on 2023-10-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_alter_healthcare_mrc_center_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcare',
            name='status',
            field=models.PositiveBigIntegerField(choices=[(0, 'Consultation'), (1, 'Dispensation'), (2, 'Expired'), (3, 'Completed')], default=0, verbose_name='Standing'),
        ),
    ]
