# Generated by Django 4.2.4 on 2023-08-28 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_alter_service_healthcenter_alter_staff_healthcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcenter',
            name='status',
            field=models.IntegerField(choices=[(0, 'Mandatory Referral Center'), (1, 'Standard Referral Center'), (2, 'Pharmacy')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicationitem',
            name='pharmacy',
            field=models.ForeignKey(default=0, limit_choices_to={'status': 'pharmacy'}, on_delete=django.db.models.deletion.RESTRICT, to='medical.healthcenter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='healthcenter',
            field=models.ForeignKey(limit_choices_to={'status__icontains': 'Referral'}, on_delete=django.db.models.deletion.RESTRICT, related_name='services', to='medical.healthcenter', verbose_name='Health Center'),
        ),
    ]
