# Generated by Django 4.2.4 on 2023-08-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_alter_medication_molecule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodgroup',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='codification',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicationtype',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
