# Generated by Django 4.2.4 on 2023-08-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_alter_medicationitem_pharmacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='practitioner',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
