# Generated by Django 4.2.4 on 2023-08-22 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_alter_speciality_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Degree name')),
                ('isActive', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('rank', models.IntegerField(default=1)),
                ('isActive', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='indicative_price',
            new_name='indicativePrice',
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='maximum_age',
            new_name='maximumAge',
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='medication_type',
            new_name='medicationType',
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='minimum_age',
            new_name='minimumAge',
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='price_margin',
            new_name='priceMargin',
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='therapeutic_route',
            new_name='therapeuticRoute',
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='waiting_period',
            new_name='waitingPeriod',
        ),
        migrations.AlterUniqueTogether(
            name='medication',
            unique_together={('name', 'medicationType', 'therapeuticRoute')},
        ),
        migrations.CreateModel(
            name='Practionner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CorpReference', models.CharField(max_length=32)),
                ('firstName', models.CharField(max_length=32)),
                ('lastName', models.CharField(max_length=128)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('degree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medical.degree')),
                ('speciality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medical.speciality')),
            ],
            options={
                'unique_together': {('firstName', 'lastName', 'dateOfBirth')},
            },
        ),
    ]
