# Generated by Django 4.2.4 on 2023-08-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0007_delete_bloodgroup_delete_standing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practionner',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=None),
        ),
    ]
